### PR TITLE
Rollup of outstanding PRs

### PR DESCRIPTION
**Pull request by rillian**
Here's all the outstanding pull requests from the upstream repository. Not the ideal rebase order, but at least it brings things up to date a bit.

Doesn't address the build failure on 1.18.0-nightly. I suspect we need another `syntex` bump to get a compatible `serde_derive`.

### CODE REVIEW

**Comment by rillian** [comment]
Fixes:
* https://github.com/Sean1708/rusty-cheddar/pull/53
* https://github.com/Sean1708/rusty-cheddar/pull/49
* https://github.com/Sean1708/rusty-cheddar/pull/45
* https://github.com/Sean1708/rusty-cheddar/pull/35

**Comment by kinetiknz** [comment]
LGTM

**Comment by kinetiknz** [comment]
> Sean1708#35

This wasn't included in the PR.

**Comment by rillian** [comment]
>>    Sean1708#35
>
> This wasn't included in the PR.

Oops, you're right. I was going to include it, but then held off because it's a breaking change. But the `Option<fn>` fix is technically also a breaking change, so I'll go ahead and do that in another PR and bump the version number.

**Pull request merged**
